// AUTO-GENERATED by scripts/build-asset-manifest.mjs
// Edit the script, not this file. Re-runs on every `npm run build`.
//
// Maps `/public/*` paths to 10-character content hashes. Consumers go
// through `assetUrl()` to get a cache-busted URL like `/Foo.webp?v=abcd`.
// Paths not in the manifest fall through to the raw URL.

export const ASSET_HASHES: Readonly<Record<string, string>> = {
  "/AppliedSciences.webp": "adb369bef7",
  "/AtomicTheory.webp": "0de6dfc373",
  "/BehaviourTrees.webp": "6d0a59aadd",
  "/BigBangTheory.webp": "d688c99ed5",
  "/BinarySearch.webp": "da70c9215c",
  "/BiologicalModularity.webp": "5f0708769e",
  "/BohrModel.webp": "8abc806962",
  "/CellTheory.webp": "3b635031d7",
  "/ChaosTheory.webp": "b9e0b03187",
  "/CognitiveTheory.webp": "54d9e6566d",
  "/ComplexAdaptiveSystems.webp": "dcb6cd0935",
  "/ComplexSystems.webp": "1232f2571a",
  "/ConservationLaws.webp": "beaff0c127",
  "/ConservationOfMass.webp": "0e6e1ab980",
  "/DNADoubleHelix.webp": "15032d10aa",
  "/DijkstrasAlgorithm.webp": "3d78649033",
  "/DistributedSystems.webp": "12d003fdf8",
  "/Ecosystems.webp": "6d29222164",
  "/FormalSciences.webp": "982a78e080",
  "/FoundationModels.webp": "4f4ee2a5e5",
  "/GOAP.webp": "ca30510d2f",
  "/GameTheory.webp": "52f31d4b7b",
  "/GeneralRelativity.webp": "8c7184fe9c",
  "/GeneralSystemsTheory.webp": "3293f82afd",
  "/GenerativeModels.webp": "12a79ec22b",
  "/GermTheory.webp": "607cfe4524",
  "/HumanKnowledge.webp": "604c95d0c7",
  "/Humanities.webp": "dd0b11d9fa",
  "/InformationTheory.webp": "a9bfd07bce",
  "/LawsOfInheritance.webp": "70576a55eb",
  "/LawsOfThermodynamics.webp": "a001f01bfc",
  "/MaxwellsEquations.webp": "41f007d0eb",
  "/ModelTheory.webp": "96dc556d21",
  "/ModularityOfMind.webp": "f42f05436e",
  "/NaturalSciences.webp": "b0e76e66ee",
  "/NervousSystem.webp": "a37815d4e1",
  "/NewtonsLaws.webp": "da1e318512",
  "/ObsidianVaults.webp": "21d80ec8a0",
  "/OperatingSystems.webp": "29f5b6d988",
  "/PeriodicLaw.webp": "c0407e4768",
  "/PlateTectonics.webp": "904ccf7dc3",
  "/Professions.webp": "4455d52fe9",
  "/QuantumMechanics.webp": "9d391ee8f6",
  "/Quicksort.webp": "1adf61b7d2",
  "/SetTheory.webp": "0f52e72aca",
  "/SocialSciences.webp": "cc1b16fe43",
  "/SoftwareModularity.webp": "0af3344ad6",
  "/SolarSystem.webp": "5b431bf14c",
  "/SpecialRelativity.webp": "3ae4c3ae69",
  "/StandardModel.webp": "540ebb1711",
  "/StandardModelCosmology.webp": "72bec40d80",
  "/TheoryOfEvolution.webp": "6886d4301b",
  "/UnityGames/BehaviourTree_Gallery/WebGL_build.data.unityweb": "2104bc7de7",
  "/UnityGames/BehaviourTree_Gallery/WebGL_build.framework.js.unityweb":
    "12380faa3f",
  "/UnityGames/BehaviourTree_Gallery/WebGL_build.loader.js": "d555e10c3c",
  "/UnityGames/BehaviourTree_Gallery/WebGL_build.wasm.unityweb": "809394d6b2",
  "/UnityGames/GOAP_Hospital/WebGL_build.data.unityweb": "7ee50f6aaa",
  "/UnityGames/GOAP_Hospital/WebGL_build.framework.js.unityweb": "156cfe5dc8",
  "/UnityGames/GOAP_Hospital/WebGL_build.loader.js": "a0f92554d8",
  "/UnityGames/GOAP_Hospital/WebGL_build.wasm.unityweb": "696c610367",
  "/UniversalGravitation.webp": "2112215aef",
  "/apple-touch-icon.png": "443be3a069",
  "/favicon-32x32.png": "089e4474cd",
  "/favicon.ico": "44bfd8d463",
  "/sci5th_Logo_Black.svg": "3fec14766a",
  "/sci5th_Logo_Blue.svg": "0c361d1043",
  "/sci5th_Logo_Pink.svg": "7673a871af",
} as const;

/**
 * Resolve a `/public/*` path to its cache-busted URL. Unknown paths fall
 * through unchanged so dev/local references don't break when an asset
 * hasn't been hashed yet (or is intentionally not under /public).
 */
export function assetUrl(path: string): string {
  const hash = ASSET_HASHES[path];
  return hash ? `${path}?v=${hash}` : path;
}
